package com.attendance.facesystem.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Stores the face embedding (numeric vector generated by the Python
 * face_recognition/OpenCV service) for a user. We do NOT store raw photos
 * permanently — only the embedding needed for matching.
 */
@Entity
@Table(name = "face_data")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class FaceData {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // Embedding stored as a comma-separated string of floats (or JSON array string)
    // returned by the Python service. Parsed back to float[] when needed for comparison.
    @Lob
    @Column(name = "embedding", columnDefinition = "TEXT", nullable = false)
    private String embedding;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }
}
